basebox-support: skip commands that are not installed
When running the script on servers, some of the commands will not
be installed.

Signed-off-by: Roger Luethi <roger.luethi@bisdn.de>

diff --git a/recipes-extended/baseboxd-tools/baseboxd-tools/basebox-support b/recipes-extended/baseboxd-tools/baseboxd-tools/basebox-support
--- a/recipes-extended/baseboxd-tools/baseboxd-tools/basebox-support
+++ b/recipes-extended/baseboxd-tools/baseboxd-tools/basebox-support
@@ -61,6 +61,11 @@ function report_result() {
 
 function log_cmd_output() {
   local cmd=("$@")
+  # Skip commands that are not present.
+  if ! exe_in_path "${cmd[0]}"; then
+    echo "${cmd[0]} not found, skipping."
+    return 0
+  fi
   # Save stdout fd 1 in fd 5 and redirect stdout to file
   exec 5>&1 >> "$OUTPUT_FILE"
   if [ -n "${LST:-""}" ]; then
